<?php

namespace Sprint\Migration;


class Version20241124231929 extends Version
{
    protected $author = "dev-artex";

    protected $description = "";

    protected $moduleVersion = "4.13.1";

    /**
     * @throws Exceptions\HelperException
     * @return bool|void
     */
    public function up()
    {
        $helper = $this->getHelperManager();
        $helper->Iblock()->saveIblockType(array (
  'ID' => 'aspro_allcorp3_content',
  'SECTIONS' => 'Y',
  'EDIT_FILE_BEFORE' => NULL,
  'EDIT_FILE_AFTER' => NULL,
  'IN_RSS' => 'N',
  'SORT' => '200',
  'LANG' => 
  array (
    'ru' => 
    array (
      'NAME' => 'Контент (aspro.allcorp3)',
      'SECTION_NAME' => 'Разделы',
      'ELEMENT_NAME' => 'Элементы',
    ),
    'en' => 
    array (
      'NAME' => 'Content (aspro.allcorp3)',
      'SECTION_NAME' => 'Sections',
      'ELEMENT_NAME' => 'Elements',
    ),
  ),
));
        $iblockId = $helper->Iblock()->saveIblock(array (
  'IBLOCK_TYPE_ID' => 'aspro_allcorp3_content',
  'LID' => 
  array (
    0 => 's1',
  ),
  'CODE' => 'aspro_allcorp3_services',
  'API_CODE' => NULL,
  'REST_ON' => 'N',
  'NAME' => 'Услуги',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'LIST_PAGE_URL' => '#SITE_DIR#services/',
  'DETAIL_PAGE_URL' => '#SITE_DIR#services/#SECTION_CODE_PATH#/#ELEMENT_CODE#/',
  'SECTION_PAGE_URL' => '#SITE_DIR#services/#SECTION_CODE_PATH#/',
  'CANONICAL_PAGE_URL' => NULL,
  'PICTURE' => NULL,
  'DESCRIPTION' => NULL,
  'DESCRIPTION_TYPE' => 'text',
  'RSS_TTL' => '24',
  'RSS_ACTIVE' => 'Y',
  'RSS_FILE_ACTIVE' => 'N',
  'RSS_FILE_LIMIT' => NULL,
  'RSS_FILE_DAYS' => NULL,
  'RSS_YANDEX_ACTIVE' => 'N',
  'XML_ID' => 'aspro_allcorp3_services_s1',
  'INDEX_ELEMENT' => 'Y',
  'INDEX_SECTION' => 'Y',
  'WORKFLOW' => 'N',
  'BIZPROC' => 'N',
  'SECTION_CHOOSER' => 'L',
  'LIST_MODE' => NULL,
  'RIGHTS_MODE' => 'S',
  'SECTION_PROPERTY' => 'Y',
  'PROPERTY_INDEX' => 'Y',
  'VERSION' => '1',
  'LAST_CONV_ELEMENT' => '0',
  'SOCNET_GROUP_ID' => NULL,
  'EDIT_FILE_BEFORE' => NULL,
  'EDIT_FILE_AFTER' => NULL,
  'SECTIONS_NAME' => 'Разделы',
  'SECTION_NAME' => 'Раздел',
  'ELEMENTS_NAME' => 'Услуги',
  'ELEMENT_NAME' => 'Услуга',
  'EXTERNAL_ID' => 'aspro_allcorp3_services_s1',
  'LANG_DIR' => '/',
  'IPROPERTY_TEMPLATES' => 
  array (
    'SECTION_PAGE_TITLE' => '{=this.Name}',
    'ELEMENT_PAGE_TITLE' => '{=this.Name}',
    'SECTION_META_TITLE' => '{=this.Name}',
    'ELEMENT_META_TITLE' => '{=this.Name}',
  ),
  'ELEMENT_ADD' => 'Добавить услугу',
  'ELEMENT_EDIT' => 'Изменить услугу',
  'ELEMENT_DELETE' => 'Удалить услугу',
  'SECTION_ADD' => 'Добавить раздел',
  'SECTION_EDIT' => 'Изменить раздел',
  'SECTION_DELETE' => 'Удалить раздел',
));
        $helper->Iblock()->saveIblockFields($iblockId, array (
  'IBLOCK_SECTION' => 
  array (
    'NAME' => 'Привязка к разделам',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => 
    array (
      'KEEP_IBLOCK_SECTION_ID' => 'N',
    ),
    'VISIBLE' => 'Y',
  ),
  'ACTIVE' => 
  array (
    'NAME' => 'Активность',
    'IS_REQUIRED' => 'Y',
    'DEFAULT_VALUE' => 'Y',
    'VISIBLE' => 'Y',
  ),
  'ACTIVE_FROM' => 
  array (
    'NAME' => 'Начало активности',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => '',
    'VISIBLE' => 'Y',
  ),
  'ACTIVE_TO' => 
  array (
    'NAME' => 'Окончание активности',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => '',
    'VISIBLE' => 'Y',
  ),
  'SORT' => 
  array (
    'NAME' => 'Сортировка',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => '0',
    'VISIBLE' => 'Y',
  ),
  'NAME' => 
  array (
    'NAME' => 'Название',
    'IS_REQUIRED' => 'Y',
    'DEFAULT_VALUE' => '',
    'VISIBLE' => 'Y',
  ),
  'PREVIEW_PICTURE' => 
  array (
    'NAME' => 'Картинка для анонса',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => 
    array (
      'FROM_DETAIL' => 'Y',
      'UPDATE_WITH_DETAIL' => 'N',
      'DELETE_WITH_DETAIL' => 'N',
      'SCALE' => 'Y',
      'WIDTH' => 700,
      'HEIGHT' => 700,
      'IGNORE_ERRORS' => 'N',
      'METHOD' => 'resample',
      'COMPRESSION' => 80,
      'USE_WATERMARK_TEXT' => 'N',
      'WATERMARK_TEXT' => '',
      'WATERMARK_TEXT_FONT' => '',
      'WATERMARK_TEXT_COLOR' => '',
      'WATERMARK_TEXT_SIZE' => '',
      'WATERMARK_TEXT_POSITION' => '',
      'USE_WATERMARK_FILE' => 'N',
      'WATERMARK_FILE' => '',
      'WATERMARK_FILE_ALPHA' => '',
      'WATERMARK_FILE_POSITION' => '',
      'WATERMARK_FILE_ORDER' => '',
    ),
    'VISIBLE' => 'Y',
  ),
  'PREVIEW_TEXT_TYPE' => 
  array (
    'NAME' => 'Тип описания для анонса',
    'IS_REQUIRED' => 'Y',
    'DEFAULT_VALUE' => 'text',
    'VISIBLE' => 'Y',
  ),
  'PREVIEW_TEXT' => 
  array (
    'NAME' => 'Описание для анонса',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => '',
    'VISIBLE' => 'Y',
  ),
  'DETAIL_PICTURE' => 
  array (
    'NAME' => 'Детальная картинка',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => 
    array (
      'SCALE' => 'Y',
      'WIDTH' => 2000,
      'HEIGHT' => 2000,
      'IGNORE_ERRORS' => 'N',
      'METHOD' => 'resample',
      'COMPRESSION' => 80,
      'USE_WATERMARK_TEXT' => 'N',
      'WATERMARK_TEXT' => '',
      'WATERMARK_TEXT_FONT' => '',
      'WATERMARK_TEXT_COLOR' => '',
      'WATERMARK_TEXT_SIZE' => '',
      'WATERMARK_TEXT_POSITION' => '',
      'USE_WATERMARK_FILE' => 'N',
      'WATERMARK_FILE' => '',
      'WATERMARK_FILE_ALPHA' => '',
      'WATERMARK_FILE_POSITION' => '',
      'WATERMARK_FILE_ORDER' => '',
    ),
    'VISIBLE' => 'Y',
  ),
  'DETAIL_TEXT_TYPE' => 
  array (
    'NAME' => 'Тип детального описания',
    'IS_REQUIRED' => 'Y',
    'DEFAULT_VALUE' => 'html',
    'VISIBLE' => 'Y',
  ),
  'DETAIL_TEXT' => 
  array (
    'NAME' => 'Детальное описание',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => '',
    'VISIBLE' => 'Y',
  ),
  'XML_ID' => 
  array (
    'NAME' => 'Внешний код',
    'IS_REQUIRED' => 'Y',
    'DEFAULT_VALUE' => '',
    'VISIBLE' => 'Y',
  ),
  'CODE' => 
  array (
    'NAME' => 'Символьный код',
    'IS_REQUIRED' => 'Y',
    'DEFAULT_VALUE' => 
    array (
      'UNIQUE' => 'Y',
      'TRANSLITERATION' => 'Y',
      'TRANS_LEN' => 100,
      'TRANS_CASE' => 'L',
      'TRANS_SPACE' => '-',
      'TRANS_OTHER' => '-',
      'TRANS_EAT' => 'Y',
      'USE_GOOGLE' => 'N',
    ),
    'VISIBLE' => 'Y',
  ),
  'TAGS' => 
  array (
    'NAME' => 'Теги',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => '',
    'VISIBLE' => 'Y',
  ),
  'SECTION_NAME' => 
  array (
    'NAME' => 'Название',
    'IS_REQUIRED' => 'Y',
    'DEFAULT_VALUE' => '',
    'VISIBLE' => 'Y',
  ),
  'SECTION_PICTURE' => 
  array (
    'NAME' => 'Картинка для анонса',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => 
    array (
      'FROM_DETAIL' => 'Y',
      'UPDATE_WITH_DETAIL' => 'N',
      'DELETE_WITH_DETAIL' => 'N',
      'SCALE' => 'Y',
      'WIDTH' => 700,
      'HEIGHT' => 700,
      'IGNORE_ERRORS' => 'N',
      'METHOD' => 'resample',
      'COMPRESSION' => 80,
      'USE_WATERMARK_TEXT' => 'N',
      'WATERMARK_TEXT' => '',
      'WATERMARK_TEXT_FONT' => '',
      'WATERMARK_TEXT_COLOR' => '',
      'WATERMARK_TEXT_SIZE' => '',
      'WATERMARK_TEXT_POSITION' => '',
      'USE_WATERMARK_FILE' => 'N',
      'WATERMARK_FILE' => '',
      'WATERMARK_FILE_ALPHA' => '',
      'WATERMARK_FILE_POSITION' => '',
      'WATERMARK_FILE_ORDER' => '',
    ),
    'VISIBLE' => 'Y',
  ),
  'SECTION_DESCRIPTION_TYPE' => 
  array (
    'NAME' => 'Тип описания',
    'IS_REQUIRED' => 'Y',
    'DEFAULT_VALUE' => 'text',
    'VISIBLE' => 'Y',
  ),
  'SECTION_DESCRIPTION' => 
  array (
    'NAME' => 'Описание',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => '',
    'VISIBLE' => 'Y',
  ),
  'SECTION_DETAIL_PICTURE' => 
  array (
    'NAME' => 'Детальная картинка',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => 
    array (
      'SCALE' => 'Y',
      'WIDTH' => 1500,
      'HEIGHT' => 1500,
      'IGNORE_ERRORS' => 'N',
      'METHOD' => 'resample',
      'COMPRESSION' => 80,
      'USE_WATERMARK_TEXT' => 'N',
      'WATERMARK_TEXT' => '',
      'WATERMARK_TEXT_FONT' => '',
      'WATERMARK_TEXT_COLOR' => '',
      'WATERMARK_TEXT_SIZE' => '',
      'WATERMARK_TEXT_POSITION' => '',
      'USE_WATERMARK_FILE' => 'N',
      'WATERMARK_FILE' => '',
      'WATERMARK_FILE_ALPHA' => '',
      'WATERMARK_FILE_POSITION' => '',
      'WATERMARK_FILE_ORDER' => '',
    ),
    'VISIBLE' => 'Y',
  ),
  'SECTION_XML_ID' => 
  array (
    'NAME' => 'Внешний код',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => '',
    'VISIBLE' => 'Y',
  ),
  'SECTION_CODE' => 
  array (
    'NAME' => 'Символьный код',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => 
    array (
      'UNIQUE' => 'Y',
      'TRANSLITERATION' => 'Y',
      'TRANS_LEN' => 100,
      'TRANS_CASE' => 'L',
      'TRANS_SPACE' => '-',
      'TRANS_OTHER' => '-',
      'TRANS_EAT' => 'Y',
      'USE_GOOGLE' => 'N',
    ),
    'VISIBLE' => 'Y',
  ),
  'LOG_SECTION_ADD' => 
  array (
    'NAME' => 'LOG_SECTION_ADD',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => NULL,
    'VISIBLE' => 'Y',
  ),
  'LOG_SECTION_EDIT' => 
  array (
    'NAME' => 'LOG_SECTION_EDIT',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => NULL,
    'VISIBLE' => 'Y',
  ),
  'LOG_SECTION_DELETE' => 
  array (
    'NAME' => 'LOG_SECTION_DELETE',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => NULL,
    'VISIBLE' => 'Y',
  ),
  'LOG_ELEMENT_ADD' => 
  array (
    'NAME' => 'LOG_ELEMENT_ADD',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => NULL,
    'VISIBLE' => 'Y',
  ),
  'LOG_ELEMENT_EDIT' => 
  array (
    'NAME' => 'LOG_ELEMENT_EDIT',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => NULL,
    'VISIBLE' => 'Y',
  ),
  'LOG_ELEMENT_DELETE' => 
  array (
    'NAME' => 'LOG_ELEMENT_DELETE',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => NULL,
    'VISIBLE' => 'Y',
  ),
));
    $helper->Iblock()->saveGroupPermissions($iblockId, array (
  'administrators' => 'X',
  'everyone' => 'R',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Город',
  'ACTIVE' => 'Y',
  'SORT' => '200',
  'CODE' => 'LINK_REGION',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '3128',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_allcorp3_regionality:aspro_allcorp3_regions',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'ID поста блога для комментариев',
  'ACTIVE' => 'Y',
  'SORT' => '200',
  'CODE' => 'BLOG_POST_ID',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'N',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '2219',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'A',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Количество комментариев',
  'ACTIVE' => 'Y',
  'SORT' => '200',
  'CODE' => 'BLOG_COMMENTS_CNT',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'N',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '2220',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'A',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Валюта',
  'ACTIVE' => 'Y',
  'SORT' => '200',
  'CODE' => 'PRICE_CURRENCY',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3027',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'Y',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => 'В цене можно использовать маркер #CURRENCY#',
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => '&#8381;',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'RUB',
    ),
    1 => 
    array (
      'VALUE' => '&euro;',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'EUR',
    ),
    2 => 
    array (
      'VALUE' => '$',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'USD',
    ),
    3 => 
    array (
      'VALUE' => 'грн.',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'UAH',
    ),
  ),
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Заказ услуги',
  'ACTIVE' => 'Y',
  'SORT' => '210',
  'CODE' => 'FORM_ORDER',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'C',
  'MULTIPLE' => 'N',
  'XML_ID' => '10',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'Y',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Да',
      'DEF' => 'Y',
      'SORT' => '500',
      'XML_ID' => 'YES',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Цена на карточке',
  'ACTIVE' => 'Y',
  'SORT' => '210',
  'CODE' => 'PRICE',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '2294',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Задать вопрос',
  'ACTIVE' => 'Y',
  'SORT' => '220',
  'CODE' => 'FORM_QUESTION',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'C',
  'MULTIPLE' => 'N',
  'XML_ID' => '11',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'Y',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Да',
      'DEF' => 'Y',
      'SORT' => '500',
      'XML_ID' => 'YES',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Старая цена',
  'ACTIVE' => 'Y',
  'SORT' => '220',
  'CODE' => 'PRICEOLD',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '2295',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'Y',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Баннер сверху',
  'ACTIVE' => 'Y',
  'SORT' => '230',
  'CODE' => 'BNR_TOP',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'C',
  'MULTIPLE' => 'N',
  'XML_ID' => '779',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Да',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'YES',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Экономия',
  'ACTIVE' => 'Y',
  'SORT' => '230',
  'CODE' => 'ECONOMY',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '2999',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Активная картинка',
  'ACTIVE' => 'Y',
  'SORT' => '240',
  'CODE' => 'BNR_TOP_IMG',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'F',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '781',
  'FILE_TYPE' => 'jpg, gif, bmp, png, jpeg',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => NULL,
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Цена для фильтра',
  'ACTIVE' => 'Y',
  'SORT' => '240',
  'CODE' => 'FILTER_PRICE',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'N',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3028',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'Y',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => 'Необходима для фильтрации по цене и подсчета общей суммы. В качестве делителя десятичной дробной части используйте точку. Пример целого числа: 1200 Пример дробного десятичного: 1200.22 Для корректной работы сайта не удаляйте данное свойство.',
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
  ),
  'SMART_FILTER' => 'Y',
  'DISPLAY_TYPE' => 'A',
  'DISPLAY_EXPANDED' => 'Y',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Прозрачная картинка',
  'ACTIVE' => 'Y',
  'SORT' => '245',
  'CODE' => 'TRANSPARENT_PICTURE',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'F',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3049',
  'FILE_TYPE' => 'jpg, gif, bmp, png, jpeg',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => NULL,
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Фоновая картинка',
  'ACTIVE' => 'Y',
  'SORT' => '250',
  'CODE' => 'BNR_TOP_BG',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'F',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '780',
  'FILE_TYPE' => 'jpg, gif, bmp, png, jpeg',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => NULL,
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Иконка (SVG)',
  'ACTIVE' => 'Y',
  'SORT' => '250',
  'CODE' => 'ICON',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'F',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3004',
  'FILE_TYPE' => 'svg',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => NULL,
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Показывать на главной',
  'ACTIVE' => 'Y',
  'SORT' => '250',
  'CODE' => 'SHOW_ON_INDEX_PAGE',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'C',
  'MULTIPLE' => 'N',
  'XML_ID' => '3007',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'Y',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Y',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'Y',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Кнопка 1 текст',
  'ACTIVE' => 'Y',
  'SORT' => '250',
  'CODE' => 'BUTTON1TEXT',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3946',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Кнопка 1 ссылка',
  'ACTIVE' => 'Y',
  'SORT' => '250',
  'CODE' => 'BUTTON1LINK',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3947',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Кнопка 1 цель',
  'ACTIVE' => 'Y',
  'SORT' => '250',
  'CODE' => 'BUTTON1TARGET',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3948',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Открыть в новой вкладке',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '_blank',
    ),
    1 => 
    array (
      'VALUE' => 'Открыть в текущей вкладке',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '_self',
    ),
    2 => 
    array (
      'VALUE' => 'Скролл к описанию',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'scroll',
    ),
  ),
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Кнопка 1 класс',
  'ACTIVE' => 'Y',
  'SORT' => '250',
  'CODE' => 'BUTTON1CLASS',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3972',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Залитая',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-default',
    ),
    1 => 
    array (
      'VALUE' => 'Полупрозрачная',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-transparent',
    ),
    2 => 
    array (
      'VALUE' => 'Прозрачная с бордером',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-transparent-bg',
    ),
  ),
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Кнопка 1 цвет',
  'ACTIVE' => 'Y',
  'SORT' => '250',
  'CODE' => 'BUTTON1COLOR',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3974',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Белая',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-white',
    ),
    1 => 
    array (
      'VALUE' => 'Красная',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-danger',
    ),
    2 => 
    array (
      'VALUE' => 'Оранжевая',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-warning',
    ),
    3 => 
    array (
      'VALUE' => 'Салатовая',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-info',
    ),
    4 => 
    array (
      'VALUE' => 'Светло-зеленая',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-success',
    ),
    5 => 
    array (
      'VALUE' => 'Темно-зеленая',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-primary',
    ),
    6 => 
    array (
      'VALUE' => 'Цвет темы',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-theme',
    ),
  ),
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Кнопка 1 атрибуты',
  'ACTIVE' => 'Y',
  'SORT' => '250',
  'CODE' => 'BUTTON1ATTR',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '15',
  'COL_COUNT' => '100',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '4011',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Кнопка 2 текст',
  'ACTIVE' => 'Y',
  'SORT' => '251',
  'CODE' => 'BUTTON2TEXT',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3949',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Кнопка 2 ссылка',
  'ACTIVE' => 'Y',
  'SORT' => '251',
  'CODE' => 'BUTTON2LINK',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3950',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Кнопка 2 цель',
  'ACTIVE' => 'Y',
  'SORT' => '251',
  'CODE' => 'BUTTON2TARGET',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3951',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Открыть в новой вкладке',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '_blank',
    ),
    1 => 
    array (
      'VALUE' => 'Открыть в текущей вкладке',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '_self',
    ),
  ),
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Кнопка 2 класс',
  'ACTIVE' => 'Y',
  'SORT' => '251',
  'CODE' => 'BUTTON2CLASS',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3973',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Залитая',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-default',
    ),
    1 => 
    array (
      'VALUE' => 'Полупрозрачная',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-transparent',
    ),
    2 => 
    array (
      'VALUE' => 'Прозрачная с бордером',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-transparent-bg',
    ),
  ),
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Кнопка 2 цвет',
  'ACTIVE' => 'Y',
  'SORT' => '251',
  'CODE' => 'BUTTON2COLOR',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3975',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Белая',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-white',
    ),
    1 => 
    array (
      'VALUE' => 'Красная',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-danger',
    ),
    2 => 
    array (
      'VALUE' => 'Оранжевая',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-warning',
    ),
    3 => 
    array (
      'VALUE' => 'Салатовая',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-info',
    ),
    4 => 
    array (
      'VALUE' => 'Светло-зеленая',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-success',
    ),
    5 => 
    array (
      'VALUE' => 'Темно-зеленая',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-primary',
    ),
    6 => 
    array (
      'VALUE' => 'Цвет темы',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'btn-theme',
    ),
  ),
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Кнопка 2 атрибуты',
  'ACTIVE' => 'Y',
  'SORT' => '251',
  'CODE' => 'BUTTON2ATTR',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '15',
  'COL_COUNT' => '100',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '4012',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Цвет шапки и текста',
  'ACTIVE' => 'Y',
  'SORT' => '260',
  'CODE' => 'BNR_TOP_COLOR',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '800',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'Y',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'светлый',
      'DEF' => 'Y',
      'SORT' => '500',
      'XML_ID' => 'light',
    ),
    1 => 
    array (
      'VALUE' => 'темный',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'dark',
    ),
  ),
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Расположение фото',
  'ACTIVE' => 'Y',
  'SORT' => '270',
  'CODE' => 'PHOTOPOS',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '115',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'Y',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'С наездом на шапку',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'TOP_ON_HEAD',
    ),
    1 => 
    array (
      'VALUE' => 'Слева',
      'DEF' => 'Y',
      'SORT' => '500',
      'XML_ID' => 'LEFT',
    ),
    2 => 
    array (
      'VALUE' => 'Справа',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'RIGHT',
    ),
    3 => 
    array (
      'VALUE' => 'Широкая (в контенте)',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'WIDE',
    ),
    4 => 
    array (
      'VALUE' => 'Над контентом (на всю ширину)',
      'DEF' => 'N',
      'SORT' => '510',
      'XML_ID' => 'TOP',
    ),
    5 => 
    array (
      'VALUE' => 'Над контентом (по ширине контента)',
      'DEF' => 'N',
      'SORT' => '520',
      'XML_ID' => 'TOP_CONTENT',
    ),
  ),
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'С наездом на шапку',
  'ACTIVE' => 'Y',
  'SORT' => '270',
  'CODE' => 'BNR_TOP_UNDER_HEADER',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'C',
  'MULTIPLE' => 'N',
  'XML_ID' => '3100',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'Y',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Да',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'YES',
    ),
  ),
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Видео (IFRAME)',
  'ACTIVE' => 'Y',
  'SORT' => '300',
  'CODE' => 'VIDEO_IFRAME',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '3091',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Видео (файл)',
  'ACTIVE' => 'Y',
  'SORT' => '300',
  'CODE' => 'VIDEO',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '3092',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => 'video',
  'USER_TYPE_SETTINGS' => 
  array (
    'BUFFER_LENGTH' => 10,
    'CONTROLBAR' => 'bottom',
    'AUTOSTART' => 'N',
    'VOLUME' => 90,
    'SKIN' => '',
    'FLASHVARS' => '',
    'WMODE_FLV' => 'transparent',
    'BGCOLOR' => 'FFFFFF',
    'COLOR' => '000000',
    'OVER_COLOR' => '000000',
    'SCREEN_COLOR' => '000000',
    'SILVERVARS' => '',
    'WMODE_WMV' => 'windowless',
    'WIDTH' => '400',
    'HEIGHT' => '300',
  ),
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Редирект',
  'ACTIVE' => 'Y',
  'SORT' => '300',
  'CODE' => 'REDIRECT',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3058',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Галерея',
  'ACTIVE' => 'Y',
  'SORT' => '360',
  'CODE' => 'PHOTOS',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'F',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '8',
  'FILE_TYPE' => 'jpg, gif, bmp, png, jpeg',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'Y',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => NULL,
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Файлы',
  'ACTIVE' => 'Y',
  'SORT' => '380',
  'CODE' => 'DOCUMENTS',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'F',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '7',
  'FILE_TYPE' => 'doc, txt, rtf, xls, xlsx, docx, pdf, jpg, jpeg, png, ppt, tif',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'Y',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => NULL,
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Партнеры',
  'ACTIVE' => 'Y',
  'SORT' => '400',
  'CODE' => 'LINK_PARTNERS',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '3093',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_allcorp3_content:aspro_allcorp3_partners',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Вакансии',
  'ACTIVE' => 'Y',
  'SORT' => '400',
  'CODE' => 'LINK_VACANCY',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '3094',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_allcorp3_content:aspro_allcorp3_vacancy',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Тизеры',
  'ACTIVE' => 'Y',
  'SORT' => '400',
  'CODE' => 'LINK_TIZERS',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '3130',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_allcorp3_content:aspro_allcorp3_front_tizers',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Статьи',
  'ACTIVE' => 'Y',
  'SORT' => '400',
  'CODE' => 'LINK_ARTICLES',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '2382',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_allcorp3_content:aspro_allcorp3_articles',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Faq',
  'ACTIVE' => 'Y',
  'SORT' => '400',
  'CODE' => 'LINK_FAQ',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '2296',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_allcorp3_content:aspro_allcorp3_faq',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Услуги',
  'ACTIVE' => 'Y',
  'SORT' => '400',
  'CODE' => 'LINK_SERVICES',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '2298',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_allcorp3_content:aspro_allcorp3_services',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Новости',
  'ACTIVE' => 'Y',
  'SORT' => '400',
  'CODE' => 'LINK_NEWS',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '2302',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_allcorp3_content:aspro_allcorp3_news',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Товары',
  'ACTIVE' => 'Y',
  'SORT' => '410',
  'CODE' => 'LINK_GOODS',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '13',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_allcorp3_catalog:aspro_allcorp3_catalog',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'Y',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Связанные товары по фильтру',
  'ACTIVE' => 'Y',
  'SORT' => '410',
  'CODE' => 'LINK_GOODS_FILTER',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3085',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '1',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => 'SAsproCustomFilterAllcorp3',
  'USER_TYPE_SETTINGS' => 
  array (
    'IBLOCK_ID' => 43,
    'IBLOCK_TYPE_ID' => false,
    'USE_OFFERS_IBLOCK' => 'N',
  ),
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Специалисты',
  'ACTIVE' => 'Y',
  'SORT' => '420',
  'CODE' => 'LINK_STAFF',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '12',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_allcorp3_content:aspro_allcorp3_staff',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'Y',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Проекты',
  'ACTIVE' => 'Y',
  'SORT' => '440',
  'CODE' => 'LINK_PROJECTS',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '67',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_allcorp3_content:aspro_allcorp3_projects',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'Y',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Отзывы клиентов',
  'ACTIVE' => 'Y',
  'SORT' => '450',
  'CODE' => 'LINK_REVIEWS',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '14',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_allcorp3_content:aspro_allcorp3_reviews',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'Y',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Акции',
  'ACTIVE' => 'Y',
  'SORT' => '460',
  'CODE' => 'LINK_SALE',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '802',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_allcorp3_content:aspro_allcorp3_sales',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Тарифы',
  'ACTIVE' => 'Y',
  'SORT' => '460',
  'CODE' => 'LINK_TARIF',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '8020',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_allcorp3_catalog:aspro_allcorp3_tarifs',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'FEATURES' => 
  array (
    0 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'DETAIL_PAGE_SHOW',
      'IS_ENABLED' => 'Y',
    ),
    1 => 
    array (
      'MODULE_ID' => 'iblock',
      'FEATURE_ID' => 'LIST_PAGE_SHOW',
      'IS_ENABLED' => 'N',
    ),
  ),
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Время на внедрение',
  'ACTIVE' => 'Y',
  'SORT' => '600',
  'CODE' => 'PROP2',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '2352',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Монтаж камеры',
  'ACTIVE' => 'Y',
  'SORT' => '600',
  'CODE' => 'FOR_SHOW_1',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '2358',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Подключение и настройка',
  'ACTIVE' => 'Y',
  'SORT' => '600',
  'CODE' => 'FOR_SHOW_2',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '2359',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Протяжка кабеля',
  'ACTIVE' => 'Y',
  'SORT' => '600',
  'CODE' => 'FOR_SHOW_3',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '2360',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Типы помещений',
  'ACTIVE' => 'Y',
  'SORT' => '600',
  'CODE' => 'TYPE_OF_BUILD',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '2375',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Авторский надзор',
  'ACTIVE' => 'Y',
  'SORT' => '600',
  'CODE' => 'AUTHOR_CONTROL',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '2376',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Подбор материалов',
  'ACTIVE' => 'Y',
  'SORT' => '600',
  'CODE' => 'MATERIAL_PICK',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '2377',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Выезд специалиста на объект',
  'ACTIVE' => 'Y',
  'SORT' => '600',
  'CODE' => 'DISEGHNER_AT_PLACE',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '2378',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Срок выполнения',
  'ACTIVE' => 'Y',
  'SORT' => '600',
  'CODE' => 'FOR_SHOW_4',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3051',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Обучение персонала',
  'ACTIVE' => 'Y',
  'SORT' => '600',
  'CODE' => 'FOR_SHOW_5',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3052',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
            $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Техническая поддержка',
  'ACTIVE' => 'Y',
  'SORT' => '600',
  'CODE' => 'FOR_SHOW_6',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '3053',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'SMART_FILTER' => 'N',
  'DISPLAY_TYPE' => 'F',
  'DISPLAY_EXPANDED' => 'N',
  'FILTER_HINT' => NULL,
));
        $helper->UserOptions()->saveElementGrid($iblockId, array (
  'views' => 
  array (
    'default' => 
    array (
      'columns' => 
      array (
        0 => '',
      ),
      'columns_sizes' => 
      array (
        'expand' => 1,
        'columns' => 
        array (
        ),
      ),
      'sticked_columns' => 
      array (
      ),
      'custom_names' => 
      array (
      ),
    ),
  ),
  'filters' => 
  array (
  ),
  'current_view' => 'default',
));

    }
}
